services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=supersafe
    ports:
      - 5431:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: