services:
  app:
    image: hello-front-dev
    build: 
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3210:5173
    container_name: hello-front-dev
  debug-helper:
    image: busybox    
volumes:
    node_modules: